name: 'Greetings'

on:
  fork:
  push:
    branches: [main]
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Hello @${{ github.actor }}! 🎉 Thank you for opening an issue. @chirantanbanik will get back to you soon. Your contribution is greatly appreciated!
          pr-message: |
            Hello @${{ github.actor }}! 🎉 Thank you for submitting a pull request. @chirantanbanik will review it shortly. Your contribution is valuable and we appreciate your efforts to improve our project.
          footer: |
            We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/chirantanbanik/Wellread/blob/master/CONTRIBUTING.MD)
